#!/usr/bin/env bash

## Copyright (C) 2020-2024 Aditya Shakya <adi1090x@gmail.com>
##
## BSPWM config file for Archcraft

## General ---------------------------------------------------#

## Bspwm config directory
BSPDIR="$HOME/.config/bspwm"

## Export bspwm/bin dir to PATH
export PATH="${PATH}:$BSPDIR/scripts"
export XDG_CURRENT_DESKTOP='bspwm'

## Run java applications without issues
export _JAVA_AWT_WM_NONREPARENTING=1
#wmname LG3D

## Screenlayout
bash "$BSPDIR/scripts/xrandr"

## Current theme ---------------------------------------------#

## Bspwm colors
BSPWM_FBC='#DE898E'
#BSPWM_FBC='#74c7ec'
BSPWM_NBC='#1E1E2E'
BSPWM_ABC='#F5C2E7'
BSPWM_PFC='#A6E3A1'

## Bspwm appearance
BSPWM_BORDER='3'
BSPWM_GAP='10'
BSPWM_SRATIO='0.50'

## Configurations --------------------------------------------#

## Manage Monitors and Workspaces
##

INTERNAL_MONITOR="eDP"
EXTERNAL_MAIN_MONITOR="DisplayPort-0"
EXTERNAL_SECOND_MONITOR="HDMI-A-0"

## Default Setup (Set 8 workspaces on each monitor)
default_workspaces() {
	for monitor in `xrandr -q | grep -w 'connected' | cut -d' ' -f1`; do
		bspc monitor "$monitor" -d '1' '2' '3' '4' '5' '6' '7' '8'
	done
}

## Two Monitors Setup (Laptop and external monitor, set 4 workspaces on each monitor)
two_monitors_workspaces() {
	bspc monitor "$EXTERNAL_MAIN_MONITOR" -d '1' '2' '3' '4'
	bspc monitor "$INTERNAL_MONITOR" -d '5' '6' '7' '8'
	bspc wm -O "$EXTERNAL_MAIN_MONITOR" "$INTERNAL_MONITOR"
}

## Two Monitors Setup (two external monitors, set 4 workspaces on each monitor)
two_monitors_without_laptop_workspaces() {
	bspc monitor "$EXTERNAL_MAIN_MONITOR" -d '1' '2' '3' '4'
	bspc monitor "$EXTERNAL_SECOND_MONITOR" -d '5' '6'
	bspc wm -O "$EXTERNAL_MAIN_MONITOR" "$EXTERNAL_SECOND_MONITOR"
}

## Three Monitors Setup (Laptop and two external monitor, 2-3-2 workspaces)
three_monitors_workspaces() {
	bspc monitor "$INTERNAL_MONITOR" -d '6' '7'
	bspc monitor "$EXTERNAL_MAIN_MONITOR" -d '1' '2' '3'
	bspc monitor "$EXTERNAL_SECOND_MONITOR" -d '4' '5'
	bspc wm -O "$EXTERNAL_MAIN_MONITOR" "$EXTERNAL_SECOND_MONITOR" "$INTERNAL_MONITOR"
}

## Uncomment only one function according to your needs

if [[ $(xrandr -q | grep -e "${EXTERNAL_MAIN_MONITOR} connected" -e "${EXTERNAL_SECOND_MONITOR} connected") ]]; then
	#two_monitors_without_laptop_workspaces
	three_monitors_workspaces
elif [[ $(xrandr -q | grep "${EXTERNAL_MAIN_MONITOR} connected") ]]; then
	two_monitors_workspaces
else
	default_workspaces
fi

## Apply bspwm configurations
bspc config border_width "$BSPWM_BORDER"
bspc config window_gap "$BSPWM_GAP"
bspc config split_ratio "$BSPWM_SRATIO"

bspc config focused_border_color "$BSPWM_FBC"
bspc config normal_border_color "$BSPWM_NBC"
bspc config active_border_color "$BSPWM_ABC"
bspc config presel_feedback_color "$BSPWM_PFC"

bspc config automatic_scheme longest_side
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config paddingless_monocle false
bspc config single_monocle false
bspc config focus_follows_pointer true
bspc config presel_feedback true
bspc config pointer_follows_focus false

## Manage all the unmanaged windows remaining from a previous session.
bspc wm --adopt-orphans

## Window rules ----------------------------------------------#

## remove all rules first
bspc rule -r *:*

## Always Floating Apps
declare -a floating=(alacritty-float Pcmanfm Onboard Yad 'Firefox:Places' \
Viewnior feh Nm-connection-editor calamares Calamares)
for i in ${floating[@]}; do
   bspc rule -a $i state=floating follow=on focus=on; done

bspc rule -a Conky state=floating manage=off
bspc rule -a stalonetray state=floating manage=off

## Autostart -------------------------------------------------#

# Kill if already running
killall -9 xsettingsd sxhkd dunst ksuperkey xfce4-power-manager bspc

# Lauch xsettingsd daemon
xsettingsd --config="$BSPDIR"/xsettingsd &

# polkit agent
if [[ ! `pidof xfce-polkit` ]]; then
	/usr/lib/xfce-polkit/xfce-polkit &
fi

# Lauch keybindings daemon
sxhkd -c "$BSPDIR"/sxhkdrc &

# Enable Super Keys For Menu
ksuperkey -e 'Super_L=Alt_L|F1' &
ksuperkey -e 'Super_R=Alt_L|F1' &

# Enable power management
xfce4-power-manager &

# Fix cursor
xsetroot -cursor_name left_ptr

# Restore wallpaper
bash ~/.fehbg

# Start mpd
exec mpd &

# Start bspwm scripts
bspbar
bspcomp
bspdunst
bspfloat &
