import = [
  "~/.config/hypr/alacritty/colors.toml",
  "~/.config/hypr/alacritty/fonts.toml"
]
live_config_reload = true

[env]
TERM = "alacritty"
WINIT_X11_SCALE_FACTOR = "1.0"

[window]
decorations = "full"
startup_mode = "Windowed"
dynamic_title = true
opacity = 1

  [window.dimensions]
  columns = 82
  lines = 24

  [window.padding]
  x = 12
  y = 12

[cursor]
unfocused_hollow = false

  [cursor.style]
  shape = "Block"
  blinking = "On"
